Repository AY2324S2-CS2113-W13-1/tp, pull requests merged in 2024-04, with the labels that each got.

#78 Tahsin beat the bot, which sent the bot into the hyperbolic time chamber
  src/main/java/seedu/duke/TicTacToe.java
Labels: type.Enhancement

#84 Fix runtest.bat infinite loop error
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
Labels: severity.Low

#147 Big merge
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/img.png
  docs/team/nicknamenic.md
  docs/team/ttasnim5.md
  src/main/java/seedu/duke/TicTacToe.java
Labels: type.Bug, documentation, type.Enhancement, priority.Medium

#150 Logging, assertions, and test codes done for Ui Component
  docs/team/jackieneoceg.md
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Render.java
  src/main/java/seedu/duke/Ui.java
  src/test/java/seedu/duke/UiTest.java
Labels: documentation

#155 Improved TTT functionality
  src/main/java/seedu/duke/TicTacToe.java
Labels: type.Enhancement

#163 Package the Ui Component for easy debugging
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Game.java
  src/main/java/seedu/duke/HangMan.java
  src/main/java/seedu/duke/TicTacToe.java
  src/main/java/seedu/duke/ui/Render.java
  src/main/java/seedu/duke/ui/TimerTutorial.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/UiTest.java
  text-ui-test/UiLog.log
  text-ui-test/UiLog.log.1
Labels: priority.Medium

#169 More Documentation
  docs/AboutUs.md
  docs/README.md
  docs/team/jackieneoceg.md
Labels: documentation

#170 Github pages please
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/test/java/seedu/duke/UiTest.java
  text-ui-test/UiLog.log
  text-ui-test/UiLog.log.lck
Labels: documentation

#177 More Documentation
  docs/UserGuide.md
  docs/team/jackieneoceg.md
Labels: documentation

#179 Included user feedback and amended UG
  docs/UserGuide.md
  src/main/java/seedu/duke/TicTacToe.java
Labels: documentation, type.Enhancement

#180 Edited my PPP a bit
  docs/team/nicknamenic.md
Labels: documentation

#182 Yet more documentation
  docs/UserGuide.md
  docs/team/img_1.png
  docs/team/jackieneoceg.md
  text-ui-test/UiLog.log
Labels: documentation
